### ISSUE TITLE
issue in dockerfile

### ISSUE THREAD

**Issue by superpoussin22** [dxa4481/gcploit#4]
Hello

You should do the copy before trying to install requirements and add labels
(also correct the RUN line with pip)

FROM python
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update && apt-get install -y google-cloud-sdk
COPY . .
RUN  pip install -r requirements.txt
CMD ["python", "-u", "main.py"]

**Comment by dxa4481** [comment]
Woops sorry about that, it's resolved and now there's an image on dockerhub https://hub.docker.com/repository/docker/dxa4481/gcploit
